<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title><?php echo $__config->site['name']; ?></title>
		<meta name="title" content="<?php echo $__config->site['name']; ?>">
		<meta name="description" content="<?php echo $__config->site['description']; ?>">

		<link rel="shortcut icon" href="/favicon.ico" />

		<link rel="stylesheet" href="<?php echo $__dynamic->css('/css/core.less'); ?>" />

		<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
		<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.10.0/jquery.validate.min.js"></script>

		<script src="<?php echo $__dynamic->js('/js/pickles.js'); ?>"></script>
		<script src="<?php echo $__dynamic->js('/js/core.js'); ?>"></script>

		<script>
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', '<?php echo $__config->site['analytics']; ?>']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
		</script>
	</head>
	<body>
		<header>
			<h1><a href="/"><?php echo $__config->site['name']; ?></a></h1>
			<hr />
		</header>

		<section id="content" class="<?php echo $__css_class; ?>">
			<?php require $__template; ?>
		</section>

		<footer>
			<hr />
			&copy; <?php echo date('Y') . ' ' . $__config->site['name']; ?>
		</footer>
	</body>
</html>
