<h2>Hello World!</h2>

<p>
	Welcome to PICKLES Starter, a starter site for your projects. This is a page that only has a template file (no module). PICKLES loads templates/__shared/index.phtml by default and in there, templates/home.phtml is loaded. If you'd like to see a page that has both a module and a template, <a href="/faq">go here</a> and to see a page has a module but no template <a href="/json">go here</a>
</p>
